<div>
    <br /><br />
    <body class="bg_main">
      <div class="home_container">

      <div id="signup">
        <div class="header">
          <h3>Welcome to Triplan!</h3>
          <h4>A place to plan your trips with family and friends together! </h4>
        </div>

        <a>Start by </a>
        <input id="cr_idea" type="button" onclick="location.href = 'http://triplan.com/idea/create'" value="Create a New Travel Idea" />
      </div>

      </div>
    </body>

</div>
