<div>
    <br /><br />
    <body class="bg_main">
      <div class="home_container">

      <div id="signup">
        <div class="header">
          <h1>Welcome to Triplan!</h1>
          <h2>A place to plan your trips with family and friends together! </h2>
        </div>

        <a class = "create">Start by </a>
        <input class="create" type="button" onclick="location.href = 'http://triplan.com/idea/create'" value="Create a New Travel Idea" />
      </div>

      </div>
    </body>

</div>
