<div>
    <br /><br />
    <body class="bg_main">
      <div class="home_container">

      <form id="signup">
        <div class="header">
            <h3>Welcome to Triplan!<br/>Help you plan your amazing trips!</h3>
            <h4>Start by create a new travel idea and share with your friends</h4>
        </div>

        <div class="inputs">
          <input id="submit" onclick="location.href = 'http://triplan.com/idea/create';"
          value="CREATE A NEW IDEA"></input>
        </div>
      </form>

      </div>
    </body>

</div>
