<!DOCTYPE html>
<html>

<head>
  <title>Triplan--help you plan your amazing trips!</title>

  <link rel="stylesheet" type="text/css" href="/css/viewer.css">
  <link rel="stylesheet" type="text/css" href="/css/latin.css">
  <link rel="stylesheet" type="text/css" href="/css/form.css">
  <link rel="stylesheet" type="text/css" href="/css/idea.css">
  <link rel="stylesheet" type="text/css" href="/css/css-stars.css">
  <link rel="stylesheet" type="text/css" href="/css/jquery-ui.css">

  <script type="text/javascript" src="/js/jquery-3.1.1.js"></script>
  <script type="text/javascript" src="/js/jquery-ui.js"></script>
  <script type="text/javascript" src="/js/jquery.barrating.min.js"></script>

  <script type="text/javascript" src="/js/jquery.validate.js"></script>
  <script type="text/javascript" src="/js/jquery.form.js"></script>

</head>

<header>
  <div class="upper">
    <a class="authen" href="http://triplan.com/user/signup">Sign up</a>
    <a class="authen" href="http://triplan.com/user/signin">Sign in</a>
    <a class="authen" href="http://triplan.com">Home</a>
  </div>
</header>
