<!DOCTYPE html>
<html> 
<head> 
<title>Triplan--help you plan your amazing trips!</title>
<link rel="stylesheet" href="/css/jquery-ui.css">
<script type="text/javascript" src="/js/jquery-3.1.1.js"></script>
<script type="text/javascript" src="/js/jquery-ui.js"></script>
<script type="text/javascript" src="/js/list.js"></script>
<link rel="stylesheet" type="text/css" href="/css/viewer.css">
<link rel="stylesheet" type="text/css" href="/css/latin.css">
<link rel="stylesheet" type="text/css" href="/css/form.css">
<script type="text/javascript">
	$( function() {
    $( ".datepicker" ).datepicker();
  } );
</script>
</head>
<header>
<div class="upper">
<a class="authen">Login</a>
<a class="authen">Signup</a>
</div>
</header>