<body class="bg_main">
<h2></h2>
<br /><br />
<br /><br />
<div class="create">
	<label class="caption">start date</label>
	<input type="text" class="datepicker"/>
	<label class="caption">end date</label>
	<input type="text" class="datepicker"/>						
	<label class="caption">destination</label>
	<select>
  <option value="Taipei">Taipei</option>
  <option value="Tokyo">Tokyo</option>
  <option value="Bangkok">Bangkok</option>
  <option value="Rangoon">Rangoon</option>
	</select>
	<input class="cr_idea" type="submit" value="Start planning" />

</div>
</body>