<?php
    session_start();
    if(!IsSet($_SESSION['loggedin']) or $_SESSION['loggedin'] != true)
    {
        header("location: http://triplan.com/user/signin");
    }
?>

<script type="text/javascript">
    $( function() {
      $( ".datepicker" ).datepicker({dateFormat: "yy-mm-dd"});
      $("#cr_idea").click(gotoedit)
    } );
    Date.prototype.addDays = function(days)
	{
	    var dat = new Date(this.valueOf());
	    dat.setDate(dat.getDate() + days);
	    return dat;
	}
    function gotoedit()
    {
      var sdate=new Date($("#sdate").val());
      var edate=new Date($("#edate").val());
      if ($("#sdate").val()>=$("#edate").val())
      {
        alert("End date must be later than start date");
      }
      else if (sdate.addDays(30)<edate)
      {
      	alert("Trip duration should be less than 30 days");
      }
      else
      {
      window.location.href="http://triplan.com/idea/edit?title="+$("#input").val()+"&sdate="+ $("#input1").val() + "&edate=" + $("#input2").val()+ "&source=" + $("#input3").val() + "&dest=" + $("#input4").val();
      }
    }

  </script>
<body class="bg_main">
<h2></h2>
<br /><br />
<br /><br />

<div class="create_container">

<div id="signup" class="create-form">

  <div class="header">
      <h3>Create a Travel Idea</h3>
  </div>
  <label class="caption">Title</label>
  <input type="text" id="input"/>
	<label class="caption">Start Date</label>
	<input type="text" class="datepicker" id="input1"/>
	<label class="caption">End Date</label>
	<input type="text" class="datepicker" id="input2"/>
	<label class="caption">Departure</label>
	<input type="text" id="input3"/>
	<label class="caption">Destination</label>
	<input type="text" id="input4"/>
	<input id="cr_idea" type="button" value="Create" />

</div>
</div>
</body>