<? session_start(); ?>
<script type="text/javascript">

 $(
  function() {

      $('.rating').barrating({
        theme: 'css-stars',
        readonly: 'true'
      });
      $('.round2').click(addItem);
      $( ".sortable" ).sortable();
      $( ".sortable" ).disableSelection();
      $("#save").click(saveIdea);
  }
);

function loadDay(evt,dnum)
{
	var i,tabcontent,tablinks;
	tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    document.getElementById(dnum).style.display = "block";
    document.getElementById("daynum").innerHTML=dnum;
}
function addItem(event)
{
	var dayid=document.getElementById("daynum").innerHTML;
	var container=document.getElementById(dayid).getElementsByClassName("sortable")[0];
	var n=document.createElement("li");
	var node = document.createElement("a");
	var text= event.target.parentNode.parentNode.getElementsByClassName("name")[0].innerHTML;
	var len=text.length-4;
	var textnode = document.createTextNode(text.substring(0,len)); 
	node.appendChild(textnode); 
	n.appendChild(node);
	container.appendChild(n);
}
function saveIdea()
{

	$.post("http://triplan.com/idea/edit",{title:$('#title').text(),source:$('#sr').text(),dest:$('#dest').text(),sdate:$('#sdate').text(),edate:$('#edate').text(),owner:$('#owner').text(),
	day01:$('#tab-1 ul').html(),
	day02:$('#tab-2 ul').html(),
	day03:$('#tab-3 ul').html(),
	day04:$('#tab-4 ul').html(),
	day05:$('#tab-5 ul').html(),
	day06:$('#tab-6 ul').html(),
	day07:$('#tab-7 ul').html(),
	day08:$('#tab-8 ul').html(),
	day09:$('#tab-9 ul').html(),
	day10:$('#tab-10 ul').html(),
	day11:$('#tab-11 ul').html(),
	day12:$('#tab-12 ul').html(),
	day13:$('#tab-13 ul').html(),
	day14:$('#tab-14 ul').html(),
	day15:$('#tab-15 ul').html(),
	day16:$('#tab-16 ul').html(),
	day17:$('#tab-17 ul').html(),
	day18:$('#tab-18 ul').html(),
	day19:$('#tab-19 ul').html(),
	day20:$('#tab-20 ul').html()
	},function(data){alert("succeed");$('#id').text(data);});

}

</script>


<var id="sdate"><? echo $this->sdate->format('Y-m-d'); ?></var>
<var id="edate"><? echo $this->edate->format('Y-m-d'); ?></var>
<var id="sr"><? echo $this->source; ?></var>
<var id="dest"><? echo $this->dest; ?></var>
<var id="owner"><? echo $_SESSION['user_id'] ?></var>
<var id="id"></var>
<div id="title">
<var><? echo $this->title; ?></var>
</div>
<body class="bg_main">
<? $d=0; echo "<p id=\"daynum\">tab-1</p>"; ?>
<div id="forsave">
<div id="alsoforsave">
<div class="block" id="bfirst"><div class="wblock"><ul id="idea_cal">
	<?
	for($i=$this->sdate,$c=0;
		($i->getTimestamp())<($this->edate->getTimestamp());
		$i->add(new DateInterval('P1D')),$c++) {
	?>
	<a href="javascript:void(0)" class="tablinks" onclick="loadDay(event,'tab-<? echo $c+1; ?>')"><li>
	<div class="round"><div class="pad"><var><? echo "D".($c+1); ?></var></div></div>
	<var><? echo $i->format('Y-m-d'); ?></var><br>
	<var class="sd"><? 
	if ($c==0) { echo $this->source."->".$this->dest;} 
	else if($i->getTimestamp()+86400==$this->edate->getTimestamp()) {echo $this->dest."->".$this->source;}
	else {echo $this->dest;}
	?></var>
	</li></a>
	<? } ?>
</ul></div></div>
</div>
<a id="save">save</a>
</div>




<div class="block" id="bsecond">

<div class="wblock">

<? $i=$this->sdate->sub(new DateInterval("P".($c+1)."D")); for($j=0;$j<=$c;$j++){ ?>
<div id="tab-<? echo $j+1; ?>" class="tabcontent">
<div class="date">
<? echo "Day ".($j+1)."  "; 
$i=$this->sdate;
echo $i->add(new DateInterval("P1D"))->format('Y-m-d');
?>
</div>

<ul class="sortable">
</ul>

</div>
<? } ?>
</div>
</div>


<div class="block" id="bthird"><div class="wblock"><ul id="idea_place">
	<? foreach ($this->xml->result as $result) { ?>
	<li class="pl">
	<div class="picture">
	<img class="place" src="<? echo "https://maps.googleapis.com/maps/api/place/photo?maxwidth=200&photoreference=".$result->photo->photo_reference."&key=AIzaSyD7q2AX3EtCIPd9i1ITISdayG8tQhjMXaQ" ?>" alt="pic">
	</div>
	<div class="pinfo">
	<a href="javascript:void(0)"><div class="round2">+</div></a>
	<p class="name"><? echo $result->name."<br>";  ?></p>
	<select class="rating" autocomplete="off">
	  <? for ($i=1;$i<=5;$i++) { ?>
	  <option value="<? echo $i; ?>" <? if(floatval($result->rating)*10%3+3==$i){echo "selected=\"selected\"";} ?>><? echo $i; ?></option>
	  <? } ?>
	</select>
	<div class="des"><p class="descr">
	<?
	 $descr=file_get_contents("https://maps.googleapis.com/maps/api/place/details/xml?placeid=".$result->place_id."&key=AIzaSyD7q2AX3EtCIPd9i1ITISdayG8tQhjMXaQ"); 
	 $reviews=simplexml_load_string($descr);
	 echo $reviews->result->review[0]->text;
	?>
	</p></div>
	</div>
	</li>
	<? } ?>
</ul></div></div>



</body>