<?php
    session_start();
    if(!IsSet($_SESSION['loggedin']) or $_SESSION['loggedin'] != true)
    {
        header("location: http://triplan.com/user/signin");
    }
?>

<script type="text/javascript">
$( function() {
  $( "#tabs" ).tabs().addClass( "ui-tabs-vertical ui-helper-clearfix" );
  $( "#tabs li" ).removeClass( "ui-corner-top" ).addClass( "ui-corner-left" );
} );
</script>


<br /><br />
<body class="bg_main">

<div class="tab_container">
<div id ="signup">
  <div class="header">
      <h3>Travel Ideas</h3>
      <p></p>
  </div>

  <div id="tabs">
    <ul>
      <li><a href="#tabs-1">My idea</a></li>
      <li><a href="#tabs-2">Others' idea</a></li>
      <li><a href="#tabs-3">Search ideas</a></li>
    </ul>
    <div id="tabs-1">
      <h2>Content heading 1</h2>
      <p>Proin elit arcu, rutrum commodo, vehicula tempus, commodo a, risus. Curabitur nec arcu. Donec sollicitudin mi sit amet mauris. Nam elementum quam ullamcorper ante. Etiam aliquet massa et lorem. </p>
    </div>
    <div id="tabs-2">
      <h2>Content heading 2</h2>
      <p>Mosuere, felis lorem euismod felis, eu ornare leo nisi vel felis. Mauris consectetur tortor et purus.</p>
    </div>
    <div id="tabs-3">
      <h2>Content heading 3</h2>
      <p>nim commodo pellentesque. Praesent eu risus hendrerit ligula tempus pretium. Curabitur lorem enim, pretium nec, feugiat nec, luctus a, lacus.</p>
      <p>Duis cursus. Maecenas ligula eros, blandit nec, pharetra at, semper at, magna. Nullam ac lacus. Nulla facilisi. Praesent viverra justo vitae neque. Praesent blandit adipiscing velit. Suspendisse po</p>
    </div>
  </div>
</div>
</div>

</body>