<script>
    $(document).ready(function() {
        $("#signup").validate({
            rules: {
                firstname: "required",
                lastname: "required",
                email: "required",
                password: "required",
                checky:"required",
                confirm_password: {
                    required: true,
                    equalTo: "#password"
                }
            }
        });
        $('#signup').ajaxForm({
            success: function(){
                alert("Sign up succeed! Please sign in now");
                window.location.replace('signin')
            },
            error: function(){
                alert("Sign up failed, please try again");
            }
        });
});
</script>


<br /><br />
<body class="bg_main">
    <div class="form_container">

        <form id="signup" method="post">
            <section class="header">
                <h3>Sign Up</h3>
                <p>Please fill out this form</p>
            </section>

            <div class="sep"></div>

            <section class="inputs">
                <input type="name" name="firstname" placeholder="First name" /> <br/>
                <input type="name" name="lastname" placeholder="Last name" /> <br/>
                <input type="email" id="email" name="email" placeholder="E-mail" autofocus /> <br/>
                <input type="password" id="password" name="password" placeholder="Password" /> <br/>
                <input type="password" id="confirm_password" name="confirm_password" placeholder="Password Confirm" /> <br/>

                <div class="checkboxy">
                    <input name="checky" id="checky" value="1" type="checkbox" /><label class="terms">I accept the terms of use</label>
                </div>

                <input id="submit" type="submit" value="SIGN UP NOW"></input>
            </section>
        </form>

    </div>
</body>
​