<script type="text/javascript" src="http://cdn.jsdelivr.net/jquery.validation/1.15.1/jquery.validate.js"></script>

<script>
    $(document).ready(function() {
        $("#signup").validate({
            rules: {
                firstname: "required",
                lastname: "required",
                email: "required",
                password: "required",
                confirm_password: {
                    required: true,
                    equalTo: "#password"
                }
            }
        });
});
</script>


<br /><br />
<body class="bg_main">
    <div class="container">

        <form id="signup">

            <div class="header">
                <h3>Sign Up</h3>
                <p>Please fill out this form</p>
            </div>

            <div class="sep"></div>

            <div class="inputs">
                <input type="email" id="email" name="email" placeholder="E-mail" autofocus /> <br/>
                <input type="password" id="password" name="password" placeholder="Password" /> <br/>
                <input type="password" id="confirm_password" name="confirm_password" placeholder="confirm_password" /> <br/>
                <input type="text" name="firstname" placeholder="First name" /> <br/>
                <input type="text" name="lastname" placeholder="Last name" /> <br/>

                <div class="checkboxy">
                    <input name="checky" id="checky" value="1" type="checkbox" /><label class="terms">I accept the terms of use</label>
                </div>

                <a id="submit" href="#">SIGN UP NOW</a>

            </div>

        </form>

    </div>
</body>
​