<br /><br />
<body class="bg_main">
    <div class="container">

        <form id="signup">

            <div class="header">
                <h3>Sign In</h3>
                <p>Please fill out this form</p>
            </div>

            <div class="sep"></div>

            <div class="inputs">

                <input type="email" placeholder="E-mail" autofocus />
                <input type="password" placeholder="Password" />

                <div class="checkboxy">
                    <input name="checky" id="checky" value="1" type="checkbox" /><label class="terms">Remember me</label>
                </div>

                <input id="submit" type="submit" value="SIGN IN"></input>
                <a href="#" class = "link">No account? Sign up for free now!</a>

            </div>

        </form>

    </div>
</body>
​