<script>
    $(document).ready(function() {
        $("#signup").validate({
            rules: {
                email: "required",
                password: "required",
            }
        });
         $('#signup').ajaxForm({
            success: function(data){
                alert("Welcome, " + data + "!" );
                window.location.replace('http://triplan.com/idea/create');
            },
            error: function(){
                alert("Invalid email or password!");
            }
        });
});
</script>


<br /><br />
<body class="bg_main">
    <div class="container">

        <form id="signup" method="post"> <!--use same css as signup form -->
            <div class="header">
                <h3>Please Sign In To Continue</h3>
                <p>Please fill out this form</p>
            </div>

            <div class="sep"></div>

            <div class="inputs">
                <input type="email" id="email" name="email" placeholder="E-mail" autofocus /> <br/>
                <input type="password" id="password" name="password" placeholder="Password" /> <br/>

                <div class="checkboxy">
                    <input name="checky" id="checky" value="1" type="checkbox" /><label class="terms">Remember me</label>
                </div>

                <input id="submit" type="submit" value="SIGN IN"></input>
                <a class="link" href="signup">No account? Sign up for free now!</a>
            </div>
        </form>

    </div>
</body>
​