<?php
    session_start();
    if(!IsSet($_SESSION['loggedin']) or $_SESSION['loggedin'] != true)
    {
        header("location: http://triplan.com/user/signin");
    }
?>

<script type="text/javascript">
$( function() {
  $( "#tabs" ).tabs().addClass( "ui-tabs-vertical ui-helper-clearfix" );
  $( "#tabs li" ).removeClass( "ui-corner-top" ).addClass( "ui-corner-left" );
} );
</script>


<br /><br />
<body class="bg_main">

<div class="tab_container">
<div id ="signup">
  <section class="header">
      <h3>My Account</h3>
      <p></p>
  </section>

  <section id="tabs">
    <ul>
      <li><a href="#tabs-1">My Information</a></li>
      <li><a href="#tabs-2">Change Password</a></li>
      <li><a href="#tabs-3">My Ideas</a></li>
    </ul>
    <article id="tabs-1">
      <h2>Account Info</h2>
      <p>Your Email : </p>
      <p>First Name : </p>
      <p>Last Name  : </p>
      <p>Date Joined: </p>
    </article>
    <article id="tabs-2">
      <h2>Content heading 2</h2>
      <p>Morbi tincidunt, dui sit amet facilisis feugiat, odio metus gravida ante, ut pharetra massa </p>
    </article>
    <article id="tabs-3">
      <h2>Content heading 3</h2>
      <p>Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti. Aliquam vulputate, pede vel vehicula .</p>
      <p>Duis cursus. Maecenas ligula eros, blandit nec, pharetra at, semper at, magna. Nullam ac lacus. Nulla facilisi. Praesent viverra justo vitae neque. Praesent blandit adipiscing velit. Suspendisse </p>
    </article>
  </section>
</div>
</div>

</body>